### PR TITLE
Windows installation

### PR DESCRIPTION
**Pull request by mabdelhack**
Updated code for python 3 and readme to reflect windows installation. I think this should either be appended to the code and readme or added as a new branch.

### CODE REVIEW

**Comment by junyanz** [comment]
Looks great. It might be better to be in a different branch. Not sure how these changes will affect Ubuntu users.

**Comment by junyanz** [comment]
I just created a windows [branch](https://github.com/junyanz/interactive-deep-colorization/tree/windows). Could you change your target branch?

**Comment by mabdelhack** [comment]
Done, thanks for creating the new branch.

**Comment by junyanz** [comment]
Thanks for your contribution. Merged.

**Comment by junyanz** [comment]
I am wondering if your guide works for Caffe model. You mentioned that "...provided a windows installation guide for the PyTorch model in Python 3.6...". But there is still some information about the Caffe model in the windows branch [README](https://github.com/junyanz/interactive-deep-colorization/blob/windows/README.md).

**Comment by mabdelhack** [comment]
I see, I think I missed some parts about Caffe. I did not test the Caffe model because in my experience, installing it on Windows was a painful process. I'll revise again.

**Comment by junyanz** [comment]
Got it. Thanks.

**Pull request merged**
