### PR TITLE
Dockerization + Python 3 update (PyQt4 --> PyQt5)

### PR DESCRIPTION
**Pull request by vwrj**
Hi!

This is my first pull request (to open-source on Github), so really excited to share it with you! 

PyQt5 is supported for Python 3, and I was having trouble running this code (with PyQt4)  and installing all dependencies. So, I converted the PyQt4 code to PyQt5 and then created a Docker container. 

I wasn't sure if you wanted to update your codebase, so I changed none of your files and just added a docker/ directory, with the new PyQt5 code inside. 

The directory's README (hopefully) has clear instructions on how to run the code in a Docker container. When I run the code, the app works and I can edit and save images as in your demo video. 

Thanks!
Vish

### CODE REVIEW

**Comment by junyanz** [comment]
Sorry for the late reply. Maybe we can create a qt5 branch rather than adding more stuff into the master branch. What do you think?

**Comment by raphink** [comment]
Qt4 is very old and has been removed from Debian and Ubuntu. I think Qt5 support should go into master.

**Review by inigo-irigaray — APPROVED** [review]

**Comment by junyanz** [comment]
@vwrj Sorry for the late reply. I just created a qt5 branch. Would it be possible to submit your PR to `qt5` branch? It would be great to keep both qt4 and qt5.

**Comment by blessedcoolant** [comment]
I found a bug in the PyQt5 implementation. The gamut on the UI does not update the color cursor correctly. It is way off from the set color.

**Comment by blshkv** [comment]
Please kill QT4 and Python2 and move on with master. There is no point supporting unsupported frameworks.

**Pull request merged**
